# Generated by Django 5.0.6 on 2024-06-13 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='I.F.O')),
                ('photo', models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Muallif rasmi')),
                ('content', models.TextField(null=True, verbose_name='Muallif haqida')),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Muallif',
                'verbose_name_plural': 'Mualliflar',
            },
        ),
        migrations.CreateModel(
            name='Kitob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('file', models.FileField(blank=True, default=None, null=True, upload_to='file/%Y/%m/%d/', verbose_name='File')),
                ('photo', models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Rasm')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilish vaqti')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Update vaqti')),
                ('is_published', models.BooleanField(default=True, verbose_name='Status')),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.author', verbose_name='Muallif')),
            ],
            options={
                'verbose_name': 'Kitob',
                'verbose_name_plural': 'Kitoblar',
                'ordering': ['-time_create'],
                'indexes': [models.Index(fields=['-time_create'], name='main_kitob_time_cr_ad23f6_idx')],
            },
        ),
    ]
